name: Pull request checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 'go.mod'
      - name: Run unit tests
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 'go.mod'
      - name: Run linter
        uses: golangci/golangci-lint-action@38e1018663fa5173f3968ea0777460d3de38f256 # v5
        with:
          args: --timeout=5m
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 'go.mod'
      - name: Setup goreleaser
        shell: bash
        run: |-
          OS="Linux"
          if [[ ${RUNNER_OS} != "Linux" ]]; then
          	echo "Unsupported OS: ${RUNNER_OS}"
          	exit 1
          fi

          # renovate-local: goreleaser-x86_64
          GORELEASER_VERSION="v2.15.2"
          # renovate-local: goreleaser-x86_64=v2.15.2
          GORELEASER_CHECKSUM_x86_64="0ebdbf0353aba566b969dde746cc4e4806f96c27aa2f3971b229a9df7611fedc"

          ARCH=$(uname -m)
          CHECKSUM="${GORELEASER_CHECKSUM_x86_64}"
          if [[ "${ARCH}" != "x86_64" ]]; then
          	echo "Unsupported architecture: ${ARCH}"
          	exit 1
          fi

          FILE="goreleaser_${OS}_${ARCH}.tar.gz"

          echo "Installing ${FILE}"
          curl -LO "https://github.com/goreleaser/goreleaser/releases/download/${GORELEASER_VERSION}/${FILE}"
          echo "${CHECKSUM} ${FILE}" | sha256sum -c
          tar -xf "${FILE}" goreleaser

          if sudo -n true &> /dev/null; then
          	sudo install -m 755 goreleaser /usr/local/bin/goreleaser
          else
          	install -m 755 goreleaser /usr/local/bin/goreleaser
          fi
          rm -f "${FILE}" goreleaser
      - name: Test build of binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |-
          goreleaser build --snapshot
